name: PR-Agent review

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  issue_comment:
    types:
      - created

concurrency:
  group: pr-agent-${{ github.event.pull_request.number || github.event.issue.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  review:
    if: >-
      github.event.sender.type != 'Bot' &&
      (
        (
          github.event_name == 'pull_request_target' &&
          (
            github.event.pull_request.head.repo.full_name == github.repository ||
            contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.pull_request.author_association)
          )
        ) ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/review') &&
          contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
        )
      )
    name: PR-Agent review
    runs-on: ubuntu-latest
    steps:
      - name: Run PR-Agent
        uses: The-PR-Agent/pr-agent@f6af7d77554ff8d26adffded077e6461329e92fa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI.API_BASE: ${{ secrets.OPENAI_API_BASE }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "synchronize"]'
